export const INVESTMENT_FINANCING_FIELD_NAMES = [
  'person',
  'investmentObjectName',
  'investmentObjectType',
  'fleetPurchasePlanned',
  'expansionInvestment',
  'purchasePriceCaptureMode',
  'purchasePrice',
  'vatRate',
  'additionalCosts',
  'operatingResourcesRequired',
  'operatingResourcesAmount',
  'acquisitionDate',
  'purchasePaymentDate',
  'plannedUsefulLifeMonths',
  'targetDesiredRate',
  'plannedFinancingDurationMonths',
  'flexibilityImportant',
  'desiredSpecialRepaymentPercent',
  'revolvingCreditPlanned',
  'additionalNeedAmount',
  'sustainabilityCriteriaFulfilled',
  'investmentObjectInsuranceDesired',
  'residualDebtInsuranceDesired',
  'interestHedgingUseful',
  'taxOptimizedBalanceNeutralDesired',
  'internalNote',
] as const;
